### ISSUE TITLE
Enettec USB

### ISSUE THREAD

**Issue by arzhurp** [s1lvester/docker-ola#1]
Hello,

Is it possible to add Enettec USB support ? 

Thank you

**Comment by s1lvester** [comment]
sure. although i don't have that device and am unable to test this. I'll try to create a branch for you to test.

**Comment by s1lvester** [comment]
@arzhurp 
Once the slooooow build process on docker-hub finishes (See: https://hub.docker.com/r/s1lvester/docker-ola/builds/ ) you can give the usb branch a try. just edit

`image: s1lvester/docker-ola:latest`

into

`image: s1lvester/docker-ola:usb`

and you should get a version in which the usb-plugins are enabled.

**Comment by arzhurp** [comment]
Hello,
Thank you for your time,
The Enettec USB Pro needs Serial USB plugin.
Sorry if I was not clear enough. 
Can you add this one ?

Thank you very much ;-)

**Comment by s1lvester** [comment]
the usb branch is compiled with ` --enable-usbserial` so it should work.

**Comment by arzhurp** [comment]
The plugin is not appearing in OLA, I only have these :
<a href='https://postimg.org/image/z0zt1ebzb/' target='_blank'><img src='https://s15.postimg.org/z0zt1ebzb/ennetc.png' border='0' alt='postimage'/></a>
And no Serial USB

**Comment by s1lvester** [comment]
I activated all plugins in the current build.

**Comment by arzhurp** [comment]
Hello !
It's working ! 
Thank you very much :)

**Comment by s1lvester** [comment]
you're welcome.
